### PR TITLE
Add Xcode and IDEAdditionalCounterpartSuffixes

### PR DESCRIPTION
**Pull request by ffittschen**
Thanks for creating this great resource!

This PR will add Xcode as application and a the `IDEAdditionalCounterpartSuffixes` key to set additional counterpart suffixes.

I didn't create a way to record screenshots yet, because this would require Xcode and a sample project on the machine that will record the screenshots, which I wanted to clarify. Would this be possible somehow? If yes I could add the recording files as well.

### CODE REVIEW

**Comment by yannbertrand** [comment]
Hey @ffittschen! Thank you for the PR 😄 

You're right, it seems like that one seems difficult to automate. I'll accept it anyways as it seems super useful.

I'm wondering, can you mix values as you like? Would something like `"ViewModel" "Interactor" ""Builder` work?
I'm not super familiar with XCode so it may have no sense but what do you think about adding other examples? (you can add as much as you like 😉)

Other than that, I'll fix the small lint issues and we're good to go 🚀

**Comment by ffittschen** [comment]
@yannbertrand Yes, any combination of values can be added, as long as they are of the format `"some string" " another string"`.

It is also possible to _replace_ all values that you can read with the `defaults read` command by using `-array` instead of `-array-add`, but I thought it would be confusing to have the same key twice just with different types.

**Comment by yannbertrand** [comment]
Oh yeah. Seems like a limitation with my generalised approach.

**Comment by yannbertrand** [comment]
Thank you again for the contribution!

**Pull request merged**
