### PR TITLE
Add various defaults

### PR DESCRIPTION
**Pull request by apexskier**
I just found this site/repo and it's exactly what I was looking for. I normally manually hunt for defaults or use https://www.defaults-write.com (which is not really organized in a useful manner), and this looks like exactly the setup I've wanted.

I have my [own system for managing defaults](https://github.com/apexskier/dotfiles/tree/main/macos/defaults) across multiple computers and have a pretty [extensive collection](https://github.com/apexskier/dotfiles/tree/main/macos/defaults/plists) I'd like to start contributing to this repository. This PR kicks things off with a number of global apple configurations, many of which come from the system preferences.

Edit: I've now added quite a bit more, and will probably keep doing so until https://github.com/yannbertrand/macos-defaults/pull/150 and https://github.com/yannbertrand/macos-defaults/pull/151 are in.

### CODE REVIEW

**Comment by yannbertrand** [comment]
What do you think about a "Global" category?

**Comment by apexskier** [comment]
I think global for `NSGlobalDomain` would make sense.

I'd personally get rid of the "custom" categories and make it all based on the `domain` (pull the `domain` key up from the keys list into the category item in the yaml file). That would enforce an organization scheme that contributors wouldn't have to make decisions about, at the expense of a little less customization. It would also get rid of the Miscellaneous section.

I think everything's currently organized by domain except `com.apple.dock` is split into "Dock", "Mission Control", and "Miscellaneous", there are several `NSGlobalDomain` items in the finder section, and "Menu Bar" would be "Menu Bar Clock".

**Comment by apexskier** [comment]
Here's an example of that organization - https://github.com/yannbertrand/macos-defaults/compare/master...apexskier:domain-organization?expand=1

**Comment by yannbertrand** [comment]
I prefer to keep the categories as is, which is easier to understand from a non-dev/end user perspective

**Comment by yannbertrand** [comment]
Is the PR still a Draft? Let me know if I can review it 🙂

**Pull request closed without merging**
