### PR TITLE
Adds "show Music song notifications"

### LINKED ISSUE #33: Show Music song notifications
`defaults write com.apple.dock itunes-notifications -bool true`

### PR DESCRIPTION
**Pull request by valentinperignon**
Fixes #33 .
I couldn't try this command on my computer, therefore the versions array is empty.

### CODE REVIEW

**Comment by yannbertrand** [comment]
It's seems the "Notifications" parameter command changed to `defaults write com.apple.Music userWantsPlaybackNotifications -bool true`.

userWantsPlaybackNotifications

I didn't get any notification on Big Sur tho 🤔.

**Comment by ValentinLab** [comment]
I'm going to change and try it ! 👍

**Comment by ValentinLab** [comment]
It works well on Catalina!
But I can't test it on Big Sur.

**Comment by yannbertrand** [comment]
Alright, it seems it's broken on Big Sur right now. Will need to review again when the official release is out.

**Review by yannbertrand — APPROVED** [review]
Thanks @ValentinLab! Will merge when Big Sur is out

**Comment by yannbertrand** [comment]
Ok anyways, I merged some Catalina PRs, merging now. Thanks again!

**Pull request merged**
